global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: rust-auth-micro-monitoring
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:9400']